name: Pipeline CI

on:
  push:
    # Se mantiene la rama master para tus despliegues
    branches: [ "master" ]

jobs:
  probar-y-subir:
    runs-on: ubuntu-latest
    steps:
    - name: Bajar código
      uses: actions/checkout@v3
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    # Se elimina el paso de 'dotnet test' ya que el Gateway no tiene proyecto de pruebas

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Construir y Subir Imagen del API Gateway
      uses: docker/build-push-action@v4
      with:
        # El contexto es la raíz del repositorio
        context: .
        # RUTA ADAPTADA: Dockerfile dentro de la carpeta API.Gateway
        file: ./API.Gateway/Dockerfile 
        push: true
        # TAG ADAPTADO: Repositorio específico para el Gateway
        tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest